In [1]:
import numpy as np

In [2]:
arr1 = np.array([1, 2, 3])
print(arr1)
print(arr1.shape)

[1 2 3]
(3,)


In [3]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)
print(arr2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [4]:
np.arange(0,10,2).reshape(5,1)


array([[0],
       [2],
       [4],
       [6],
       [8]])

In [5]:
#statistical concept
np.mean(arr1)
np.std(arr1)
#normalized data
normalizedData = (arr1 - np.mean(arr1))/np.std(arr1)
print(normalizedData)

[-1.22474487  0.          1.22474487]


In [6]:
#logical operation
data = np.array([1, 2, 3, 4, 5,6,7,8,9])
print(data[data>5])

[6 7 8 9]
